Resolves SSL error
The issue is caused by a conflict between gevent's monkey-patching (used
by Locust) and SSL. The monkey-patching happens too late, after SSL has
already been imported, causing a recursion error.

```
  File "/Users/greg/.asdf/installs/python/3.9.6/lib/python3.9/ssl.py",
line 586, in
  minimum_version
      super(SSLContext, SSLContext).minimum_version.__set__(self, value)
    [Previous line repeated 488 more times]
    File "/Users/greg/.asdf/installs/python/3.9.6/lib/python3.9/ssl.py",
line 584, in
  minimum_version
      if value == TLSVersion.SSLv3:
  RecursionError: maximum recursion depth exceeded while calling a
Python object
```